# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  workflow_dispatch:

jobs:
    python-build-n-publish:
        name: Build and publish Python distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Initialize Python 3.9
              uses: actions/setup-python@v1
              with:
                python-version: 3.9

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip

            - name: Publish distribution to PyPI
              uses: pypa/gh-action-pypi-publish@master
              with:
                username: __token__
                password: ${{ secrets.Test }}
                repository_url: https://upload.pypi.org/legacy/
